// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxExlDQkIljNK5UJ_ONfDLxqjiSQ60ygY',
    appId: '1:259382682905:web:9d6cfcb1483a5eef771188',
    messagingSenderId: '259382682905',
    projectId: 'bookcharm-64903',
    authDomain: 'bookcharm-64903.firebaseapp.com',
    storageBucket: 'bookcharm-64903.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1odvKuS-aK8MCUHP7lY_RCAoghy-g1T4',
    appId: '1:259382682905:android:95b4217bc6db362d771188',
    messagingSenderId: '259382682905',
    projectId: 'bookcharm-64903',
    storageBucket: 'bookcharm-64903.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWk8wZty1QSFTnSM36seTqEBc7dkcxx0Q',
    appId: '1:259382682905:ios:d42149044bd589fe771188',
    messagingSenderId: '259382682905',
    projectId: 'bookcharm-64903',
    storageBucket: 'bookcharm-64903.appspot.com',
    iosBundleId: 'com.example.bookCharm',
  );
}
